---
title: "Homework05"
output:
  html_document:
    theme: yeti
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
install.packages('tidyverse', repos = "http://cran.us.r-project.org")
install.packages('tidymodels', repos = "http://cran.us.r-project.org")
install.packages('ggplot2', repos = "http://cran.us.r-project.org")
install.packages('visdat', repos = "http://cran.us.r-project.org")
install.packages("corrplot", repos = "http://cran.us.r-project.org")
install.packages("discrim", repos = "http://cran.us.r-project.org")
install.packages("rlang", repos = "http://cran.us.r-project.org")
installed.packages("glmnet", repos = "http://cran.us.r-project.org")
library(tidyverse)
library(tidymodels)
library(ggplot2)
library(visdat)
library(corrplot)
library(discrim)
library(klaR)
library(yardstick)
library(glmnet)
```


## Question 1
```{r}
install.packages('janitor', repos = "http://cran.us.r-project.org")
library(janitor)
```

```{r}
set.seed(231)
data = read.csv('data/Pokemon.csv') %>% clean_names()
head(data)
```

By clean_names() fuction, column names can be neatly organized. '#' symbol chages to 'number', 'space' change to '_' and all letters change to lowercase. So we can manipulate the data easier as calling the column cames such as data$number.


## Question 2
```{r}
data %>% ggplot(aes(x = fct_infreq(data$type_1))) + 
  geom_bar()
```
```{r}
table(data$type_1)
```

There are 18 species in type_1, and very few 'Flying'.

```{r}
newdata = data[data$type_1 == 'Bug' | data$type_1 == 'Fire' | data$type_1 == 'Grass' | 
                       data$type_1 == 'Normal' | data$type_1 == 'Water' | 
                       data$type_1 == 'Psychic', ]
```

```{r}
newdata$type_1 = factor(newdata$type_1)
newdata$legendary = factor(newdata$legendary)
```


## Question 3
```{r}
data_split = initial_split(data, prop = 0.70,
                                strata = type_1)
data_train = training(data_split)
data_test = testing(data_split)

print(c(dim(data_train), dim(data_test)))
```

```{r}
cv_folds <- vfold_cv(data_train, v = 5, strata = type_1)
```


## Question 4
```{r}
pokemon_recipe = recipe(type_1 ~ legendary + generation + sp_atk + attack + speed +
                                defense + hp + sp_def,
                        data = data_train) %>%
        step_dummy(legendary, generation) %>%
        step_center(all_predictors()) %>%
        step_scale(all_predictors())
```


## Question 5
```{r}
elastic_net = linear_reg(mixture = tune(), penalty = tune()) %>%
  set_mode("regression") %>%
  set_engine("glmnet")
```

```{r}
elastic_wkflow = workflow() %>%
        add_recipe(pokemon_recipe) %>%
        add_model(elastic_net)
```

```{r}
mixture_param <- parameters(penalty(range = c(-5, 5)), mixture())

regular_grid <- grid_regular(mixture_param, levels = 10)

regular_grid %>% 
  ggplot(aes(x = mixture, y = penalty)) +
  geom_point() +
  scale_y_log10()

regular_grid

penalty_grid <- grid_regular(penalty(range = c(-5, 5)), levels = 50)
penalty_grid
```


## Question 6
```{r}
tune_res <- tune_grid(
  elastic_wkflow,
  resamples = cv_folds, 
  grid = regular_grid)

tune_res
```

```{r}
autoplot(tune_res)
```


## Question 7
```{r}
best_penalty = select_best(tune_res, metric = "roc_auc")

final = finalize_workflow(elastic_wkflow, best_penalty)

final_fit = fit(final, data = data_train)

augment(final_fit, new_data = data_test) %>%
  roc_auc(truth = type_1, estimate = .pred)
```


## Question 8
```{r}

```




